schema: dashbye/config/v2
project: .
resources: store
browser:
  endpoint: http://127.0.0.1:9333
targets:
  chrome:
    artifact: release/xtoc-chrome-v0.7.0.zip
    itemId: nbdgpckkcfkomnmdefinikjijgljgjfp
    language: English – en (default)
  edge:
    artifact: release/xtoc-edge-v0.7.0.zip
    productId: 4cc2402b-2567-46af-9e46-384c556ffb0e
    language: English – en (default)
  firefox:
    artifact: release/xtoc-firefox-v0.7.0.zip
    addon: xtoc@arieszhou.com
